### ISSUE TITLE
Compile error in vs2012 

### ISSUE THREAD

**Issue by crosslife** [chukong/CocosStudioSamples#33]
ZipUtils.cpp

\cocos2d-x\cocos2dx\platform\android\ccgl.h

“GLES2/gl2platform.h”: No such file or directory

Every sample got the same error.

need any configuration?

**Comment by linshun** [comment]
Cocos Studio has been EOL'd as of April 2016. There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for Mac and Windows.
This version of Cocos Studio requires version v3.10 of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
