### ISSUE TITLE
README.md wrong introduction

### ISSUE THREAD

**Issue by lp43** [chukong/CocosStudioSamples#35]
I want to open DemoBag sample,
I checked out to tag/2.1.5 as README.md wrote,
it showed:

CocoStudioSamples/cocos2d-x/extensions/CocoStudio/Json/lib_json/json_internalarray.inl: No such file or directory

It really doesn't have CocosStudio directory in version 2.1.5,
please check it out and fix the README.md
Thanks.

ps,
Don't you really feel that changing usage(class name, method name,etc.) in every cocos version is a disaster?

**Comment by phamtanlong** [comment]
I have seen that error, and my solution is so stupid, but it works.
That is:
create all files that make error.
it means, create folder lib_json
after that, create file json_internalarray.inl

Hope you can use this solution
