### ISSUE TITLE
all of demo   has been problem....

### ISSUE THREAD

**Issue by kangminswo** [chukong/CocosStudioSamples#39]
DemoFishingjoy

2.2.1/projects/fortune2/classes/HelloWorldScene.cpp:33:29: Use of undeclared identifier 'CCSSceneReader'; did you mean 'SceneReader'?

/Users/MinSeoKang/Downloads/cocos2d-x-2.2.1/projects/fortune2/classes/HelloWorldScene.cpp:53:2: Use of undeclared identifier 'CCSSceneReader'; did you mean 'SceneReader'?

/Users/MinSeoKang/Downloads/cocos2d-x-2.2.1/projects/fortune2/classes/HelloWorldScene.cpp:55:32: No member named 'instance' in 'cocos2d::extension::UIHelper'

DemoCowboyGame

/Users/MinSeoKang/Downloads/cocos2d-x-2.2.1/projects/fortune2/classes/HelloWorldScene.cpp:53:2: Use of undeclared identifier 'CCSSceneReader'; did you mean 'SceneReader'?

DemoGame

/Users/MinSeoKang/Downloads/cocos2d-x-2.2.1/projects/fortune2/classes/HelloWorldScene.cpp:88:22: No member named 'CCSSceneReader' in namespace 'cocos2d::extension'; did you mean 'SceneReader'?

/Users/MinSeoKang/Downloads/cocos2d-x-2.2.1/projects/fortune2/classes/HelloWorldScene.cpp:90:32: No member named 'instance' in 'cocos2d::extension::UIHelper'

DemoGameScnen

/Users/MinSeoKang/Downloads/cocos2d-x-2.2.1/projects/fortune2/classes/HelloWorldScene.cpp:33:23: Use of undeclared identifier 'CCSSceneReader'; did you mean 'SceneReader'?

/Users/MinSeoKang/Downloads/cocos2d-x-2.2.1/projects/fortune2/classes/HelloWorldScene.cpp:53:32: No member named 'instance' in 'cocos2d::extension::UIHelper'

SampleChangeEquip

/Users/MinSeoKang/Downloads/cocos2d-x-2.2.1/projects/fortune2/classes/Bag.cpp:310:22: No member named 'CCSSceneReader' in namespace 'cocos2d::extension'; did you mean 'SceneReader'?

/Users/MinSeoKang/Downloads/cocos2d-x-2.2.1/projects/fortune2/classes/Bag.cpp:312:32: No member named 'instance' in 'cocos2d::extension::UIHelper'

**Comment by linshun** [comment]
Cocos Studio has been EOL'd as of April 2016. There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for Mac and Windows.
This version of Cocos Studio requires version v3.10 of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
