### ISSUE TITLE
CocoStudioSamples-master/extensions/CocoStudio/Json/lib_json/json_internalarray.inl: No such file or directory

### ISSUE THREAD

**Issue by iSynth** [chukong/CocosStudioSamples#50]
![2014-11-10 10 14 45 am](https://cloud.githubusercontent.com/assets/7373364/4972301/47361926-68a9-11e4-8443-792a0d4df55e.jpg)

**Comment by linshun** [comment]
Cocos Studio has been EOL'd as of April 2016. There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for Mac and Windows.
This version of Cocos Studio requires version v3.10 of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
