### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by minhtoantm** [chukong/CocosStudioSamples#51]
Please check it, my device is Nexus 5 with Android 5
Log crash:

12-01 16:35:05.799: D/AndroidRuntime(18703): Shutting down VM
12-01 16:35:05.817: E/AndroidRuntime(18703): FATAL EXCEPTION: main
12-01 16:35:05.817: E/AndroidRuntime(18703): Process: com.cocosstudio.demo, PID: 18703
12-01 16:35:05.817: E/AndroidRuntime(18703): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.cocosstudio.demo/com.cocosstudio.demo.AppActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.app.ActivityThread.access$800(ActivityThread.java:144)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.os.Handler.dispatchMessage(Handler.java:102)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.os.Looper.loop(Looper.java:135)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.app.ActivityThread.main(ActivityThread.java:5221)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at java.lang.reflect.Method.invoke(Native Method)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at java.lang.reflect.Method.invoke(Method.java:372)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
12-01 16:35:05.817: E/AndroidRuntime(18703): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.content.ContextWrapper.getResources(ContextWrapper.java:85)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.view.ContextThemeWrapper.getResources(ContextThemeWrapper.java:74)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.view.View.<init>(View.java:3570)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.view.View.<init>(View.java:3675)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.widget.TextView.<init>(TextView.java:634)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.widget.Button.<init>(Button.java:111)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.widget.Button.<init>(Button.java:107)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.widget.Button.<init>(Button.java:103)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.widget.Button.<init>(Button.java:99)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at com.cocosstudio.demo.AppActivity.<init>(AppActivity.java:35)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at java.lang.reflect.Constructor.newInstance(Native Method)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at java.lang.Class.newInstance(Class.java:1572)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.app.Instrumentation.newActivity(Instrumentation.java:1065)
12-01 16:35:05.817: E/AndroidRuntime(18703):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2199)
12-01 16:35:05.817: E/AndroidRuntime(18703):    ... 10 more
12-01 16:36:13.128: D/AndroidRuntime(19133): Shutting down VM
12-01 16:36:13.134: E/AndroidRuntime(19133): FATAL EXCEPTION: main
12-01 16:36:13.134: E/AndroidRuntime(19133): Process: com.cocosstudio.demo, PID: 19133
12-01 16:36:13.134: E/AndroidRuntime(19133): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.cocosstudio.demo/com.cocosstudio.demo.AppActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.app.ActivityThread.access$800(ActivityThread.java:144)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.os.Handler.dispatchMessage(Handler.java:102)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.os.Looper.loop(Looper.java:135)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.app.ActivityThread.main(ActivityThread.java:5221)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at java.lang.reflect.Method.invoke(Native Method)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at java.lang.reflect.Method.invoke(Method.java:372)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
12-01 16:36:13.134: E/AndroidRuntime(19133): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.content.ContextWrapper.getResources(ContextWrapper.java:85)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.view.ContextThemeWrapper.getResources(ContextThemeWrapper.java:74)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.view.View.<init>(View.java:3570)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.view.View.<init>(View.java:3675)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.widget.TextView.<init>(TextView.java:634)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.widget.Button.<init>(Button.java:111)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.widget.Button.<init>(Button.java:107)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.widget.Button.<init>(Button.java:103)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.widget.Button.<init>(Button.java:99)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at com.cocosstudio.demo.AppActivity.<init>(AppActivity.java:35)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at java.lang.reflect.Constructor.newInstance(Native Method)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at java.lang.Class.newInstance(Class.java:1572)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.app.Instrumentation.newActivity(Instrumentation.java:1065)
12-01 16:36:13.134: E/AndroidRuntime(19133):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2199)
12-01 16:36:13.134: E/AndroidRuntime(19133):    ... 10 more

**Comment by linshun** [comment]
Cocos Studio has been EOL'd as of April 2016. There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for Mac and Windows.
This version of Cocos Studio requires version v3.10 of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
